apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ykwj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ykwj
    app.kubernetes.io/part-of: byoc-app-binx
  name: ykwj
spec:
  rules:
  - host: ykwj-byoc-eczb-tenant.apps.459ba87d644107fb26d4.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ykwj
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
